local keyname = {
    "scancode0",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "KP_0",
    "KP_1",
    "KP_2",
    "KP_3",
    "KP_4",
    "KP_5",
    "KP_6",
    "KP_7",
    "KP_8",
    "KP_9",
    "KP_DIVIDE",
    "KP_MULTIPLY",
    "KP_MINUS",
    "KP_PLUS",
    "KP_ENTER",
    "KP_DEL",
    "<",
    "[",
    "]",
    "SEMICOLON",
    "'",
    -- "`",
    ",",
    ".",
    "/",
    "\\",
    "-",
    "=",
    "ENTER",
    "SPACE",
    "BACKSPACE",
    "TAB",
    "CAPSLOCK",
    "NUMLOCK",
    "ESCAPE",
    "SCROLLLOCK",
    "INS",
    "DEL",
    "HOME",
    "END",
    "PGUP",
    "PGDN",
    "PAUSE",
    "SHIFT",
    "RSHIFT",
    "ALT",
    "RALT",
    "CTRL",
    "RCTRL",
    "LWIN",
    "RWIN",
    "APP",
    "UPARROW",
    "LEFTARROW",
    "DOWNARROW",
    "RIGHTARROW",
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    -- "CAPSLOCKTOGGLE",
    -- "NUMLOCKTOGGLE",
    -- "SCROLLLOCKTOGGLE",
    -- "AC_BACK",
    -- "AC_BOOKMARKS",
    -- "AC_FORWARD",
    -- "AC_HOME",
    -- "AC_REFRESH",
    -- "AC_SEARCH",
    -- "AC_STOP",
    -- "AGAIN",
    -- "ALTERASE",
    -- "AMPERSAND",
    -- "ASTERISK",
    -- "AUDIOMUTE",
    -- "AUDIONEXT",
    -- "AUDIOPLAY",
    -- "AUDIOPREV",
    -- "AUDIOSTOP",
    -- "BRIGHTNESSDOWN",
    -- "BRIGHTNESSUP",
    -- "CALCULATOR",
    -- "CANCEL",
    -- "CARET",
    -- "CLEAR",
    -- "CLEARAGAIN",
    -- "COLON",
    -- "COMPUTER",
    -- "COPY",
    -- "CRSEL",
    -- "CURRENCYSUBUNIT",
    -- "CURRENCYUNIT",
    -- "CUT",
    -- "DECIMALSEPARATOR",
    -- "DISPLAYSWITCH",
    -- "DOLLAR",
    -- "EJECT",
    -- "EXCLAIM",
    -- "EXECUTE",
    -- "EXSEL",
    -- "F13",
    -- "F14",
    -- "F15",
    -- "F16",
    -- "F17",
    -- "F18",
    -- "F19",
    -- "F20",
    -- "F21",
    -- "F22",
    -- "F23",
    -- "F24",
    -- "FIND",
    -- "GREATER",
    -- "HELP",
    -- "KBDILLUMDOWN",
    -- "KBDILLUMTOGGLE",
    -- "KBDILLUMUP",
    -- "KP_00",
    -- "KP_000",
    -- "KP_A",
    -- "KP_AMPERSAND",
    -- "KP_AT",
    -- "KP_B",
    -- "KP_BACKSPACE",
    -- "KP_BINARY",
    -- "KP_C",
    -- "KP_CLEAR",
    -- "KP_CLEARENTRY",
    -- "KP_COLON",
    -- "KP_COMMA",
    -- "KP_D",
    -- "KP_DBLAMPERSAND",
    -- "KP_DBLVERTICALBAR",
    -- "KP_DECIMAL",
    -- "KP_E",
    -- "KP_EQUALS",
    -- "KP_EQUALSAS400",
    -- "KP_EXCLAM",
    -- "KP_F",
    -- "KP_GREATER",
    -- "KP_HASH",
    -- "KP_HEXADECIMAL",
    -- "KP_LEFTBRACE",
    -- "KP_LEFTPAREN",
    -- "KP_LESS",
    -- "KP_MEMADD",
    -- "KP_MEMCLEAR",
    -- "KP_MEMDIVIDE",
    -- "KP_MEMMULTIPLY",
    -- "KP_MEMRECALL",
    -- "KP_MEMSTORE",
    -- "KP_MEMSUBTRACT",
    -- "KP_OCTAL",
    -- "KP_PERCENT",
    -- "KP_PLUSMINUS",
    -- "KP_POWER",
    -- "KP_RIGHTBRACE",
    -- "KP_RIGHTPAREN",
    -- "KP_SPACE",
    -- "KP_TAB",
    -- "KP_VERTICALBAR",
    -- "KP_XOR",
    -- "LEFTPAREN",
    -- "MEDIASELECT",
    -- "OPER",
    -- "OUT",
    -- "PASTE",
    -- "PERCENT",
    -- "POWER",
    -- "PRINTSCREEN",
    -- "PRIOR",
    -- "QUESTION",
    -- "QUOTEDBL",
    -- "RETURN2",
    -- "RIGHTPAREN",
    -- "SELECT",
    -- "SEPARATOR",
    -- "SLEEP",
    -- "STOP",
    -- "SYSREQ",
    -- "THOUSANDSSEPARATOR",
    -- "UNDERSCORE",
    -- "UNDO",
    -- "VOLUMEDOWN",
    -- "VOLUMEUP",
    -- "INVERTED_EXCLAMATION_MARK",
    -- "CENT_SIGN",
    -- "POUND_SIGN",
    -- "CURRENCY_SIGN",
    -- "YEN_SIGN",
    -- "BROKEN_BAR",
    -- "SECTION_SIGN",
    -- "DIAERESIS",
    -- "COPYRIGHT_SIGN",
    -- "FEMININE_ORDINAL_INDICATOR",
    -- "LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK",
    -- "NOT_SIGN",
    -- "REGISTERED_SIGN",
    -- "MACRON",
    -- "DEGREE_SYMBOL",
    -- "PLUS_MINUS_SIGN",
    -- "SUPERSCRIPT_TWO",
    -- "SUPERSCRIPT_THREE",
    -- "ACUTE_ACCENT",
    -- "MICRO_SIGN",
    -- "PILCROW_SIGN",
    -- "MIDDLE_DOT",
    -- "CEDILLA",
    -- "SUPERSCRIPT_ONE",
    -- "MASCULINE_ORDINAL_INDICATOR",
    -- "RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK",
    -- "VULGAR_FRACTION_ONE_QUARTER",
    -- "VULGAR_FRACTION_ONE_HALF",
    -- "VULGAR_FRACTION_THREE_QUARTERS",
    -- "INVERTED_QUESTION_MARK",
    -- "MULTIPLICATION_SIGN",
    -- "SHARP_S",
    -- "A_WITH_GRAVE",
    -- "A_WITH_ACUTE",
    -- "A_WITH_CIRCUMFLEX",
    -- "A_WITH_TILDE",
    -- "A_WITH_DIAERESIS",
    -- "A_WITH_RING_ABOVE",
    -- "C_WITH_CEDILLA",
    -- "E_WITH_GRAVE",
    -- "E_WITH_ACUTE",
    -- "E_WITH_CIRCUMFLEX",
    -- "E_WITH_DIAERESIS",
    -- "I_WITH_GRAVE",
    -- "I_WITH_ACUTE",
    -- "I_WITH_CIRCUMFLEX",
    -- "I_WITH_DIAERESIS",
    -- "N_WITH_TILDE",
    -- "O_WITH_GRAVE",
    -- "O_WITH_ACUTE",
    -- "O_WITH_CIRCUMFLEX",
    -- "O_WITH_TILDE",
    -- "O_WITH_DIAERESIS",
    -- "DIVISION_SIGN",
    -- "O_WITH_STROKE",
    -- "U_WITH_GRAVE",
    -- "U_WITH_ACUTE",
    -- "U_WITH_CIRCUMFLEX",
    -- "U_WITH_DIAERESIS",
    -- "Y_WITH_ACUTE",
    -- "THORN",
    -- "Y_WITH_DIAERESIS",
    -- "EURO_SIGN",
    -- "TILDE",
    -- "LEFT_CURLY_BRACKET",
    -- "RIGHT_CURLY_BRACKET",
    -- "VERTICAL_BAR",
    -- "KEY_CYRILLIC_YU",
    -- "KEY_CYRILLIC_E",
    -- "KEY_CYRILLIC_HARD_SIGN",
    -- "KEY_CYRILLIC_HA",
    -- "KEY_CYRILLIC_IO",
    -- "KEY_CYRILLIC_ZHE",
    -- "KEY_CYRILLIC_BE",
    -- "NONUSHASH",
    -- "NONUSBACKSLASH",
    "MENU",
    "MOUSE1",
    "MOUSE2",
    "MOUSE3",
    "MOUSE4",
    "MOUSE5",
    "MWHEELUP",
    "MWHEELDOWN",
    -- "JOY1",
    -- "JOY2",
    -- "JOY3",
    -- "JOY4",
    -- "JOY5",
    -- "JOY6",
    -- "JOY8",
    -- "JOY9",
    -- "JOY10",
    -- "JOY11",
    -- "JOY12",
    -- "JOY13",
    -- "JOY14",
    -- "JOY15",
    -- "JOY16",
    -- "JOY17",
    -- "JOY18",
    -- "JOY19",
    -- "JOY20",
    -- "JOY21",
    -- "JOY22",
    -- "JOY23",
    -- "JOY24",
    -- "JOY25",
    -- "JOY26",
    -- "JOY27",
    -- "JOY28",
    -- "JOY29",
    -- "JOY30",
    -- "JOY31",
    -- "JOY32",
    -- "POV_UP",
    -- "POV_RIGHT",
    -- "POV_DOWN",
    -- "POV_LEFT",
    -- "X_AXIS_POS",
    -- "X_AXIS_NEG",
    -- "Y_AXIS_POS",
    -- "Y_AXIS_NEG",
    -- "Z_AXIS_POS",
    -- "Z_AXIS_NEG",
    -- "R_AXIS_POS",
    -- "R_AXIS_NEG",
    -- "U_AXIS_POS",
    -- "U_AXIS_NEG",
    -- "V_AXIS_POS",
    -- "V_AXIS_NEG",
    -- "MOUSE_X",
    -- "MOUSE_Y",
    -- "MOUSE_WHEEL",
    -- "X_AXIS",
    -- "Y_AXIS",
    -- "Z_AXIS",
    -- "R_AXIS",
    -- "U_AXIS",
    -- "V_AXIS"
}


local text = "unbindall\n"
local bind = assert(io.open("profile.cfg", "w"))



for i = 1,#keyname do
    k = keyname[i]
    text = text .. string.format([[bind %s +_%s;alias +_%s "alias $ +%s;#";alias -_%s "alias $ -%s;#"]], k, k, k, k, k, k) .. "\n"
end
bind:write(text)
bind:close()